plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects --exclude /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/Exclude-subjects-1000G.txt --make-bed --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP1
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP1 --update-map /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/Chromosome-subjects-1000G.txt --update-chr --make-bed --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP2
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP2 --update-map /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/Position-subjects-1000G.txt --make-bed --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP3
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP3 --flip /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/Strand-Flip-subjects-1000G.txt --make-bed --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP4
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/TEMP4 --a2-allele /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/Force-Allele1-subjects-1000G.txt --make-bed --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 1 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr1
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 1 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr1
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 2 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr2
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 2 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr2
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 3 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr3
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 3 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr3
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 4 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr4
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 4 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr4
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 5 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr5
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 5 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr5
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 6 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr6
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 6 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr6
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 7 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr7
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 7 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr7
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 8 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr8
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 8 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr8
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 9 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr9
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 9 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr9
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 10 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr10
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 10 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr10
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 11 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr11
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 11 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr11
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 12 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr12
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 12 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr12
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 13 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr13
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 13 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr13
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 14 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr14
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 14 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr14
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 15 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr15
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 15 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr15
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 16 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr16
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 16 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr16
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 17 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr17
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 17 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr17
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 18 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr18
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 18 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr18
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 19 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr19
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 19 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr19
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 20 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr20
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 20 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr20
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 21 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr21
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 21 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr21
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 22 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr22
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 22 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr22
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --make-bed --chr 23 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr23
plink --bfile /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated --real-ref-alleles --recode vcf --chr 23 --out /mnt/nfs/gigantor/ifs/DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/output_1000G/plink_snp_cr/subjects-updated-chr23
rm plink_snp_cr/TEMP*
