plink_genotype_file: /DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/test_data_sample/input/subjects
req_scripts: /DCEG/CGF/Bioinformatics/Production/Shilpa/Scripts/PreImputePipeline/tools
strand_chain_file: None
ref_file: /DCEG/CGF/Bioinformatics/Production/software/PreImputePipeline/Ref_files/1000G/1000GP_Phase3_combined.legend
mind: 0.05
geno: 0.05
hwe: 1e-06
maf: 0.01
pop: ALL
num_samples: 238
start_time: Thu Jul 25 11:40:50 2024
